export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  NOT_TRIP_OWNER: 'NOT_TRIP_OWNER',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NEGATIVE_AMOUNT: 'NEGATIVE_AMOUNT',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;
